name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm install
    - run: npm install -g gatsby-cli
    - run: gatsby build
    
