on: push
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
      uses: uses: burnett01/rsync-deployments@4.1
      with: 
        switches: -avzr --delete
        path: public/
        remote_path: /var/www/exploro.one/
        remote_host: 173.82.16.201
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
    
