on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          skip-publish: true
      - name: Rsync
        uses: Burnett01/rsync-deployments@4.1
        with: 
          switches: -avzr --delete
          path: /public/
          remote_port: 22963
          remote_path: /var/www/exploro.one/
          remote_host: 173.82.16.201
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
        

  
